import {Link} from '@/i18n/navigation';
import PageHero from '@/components/PageHero';

export default function CoachingMentoringPage() {
  return (
    <>
      <PageHero
        breadcrumb={<><Link href="/">Home</Link> / <Link href="/services">Support Services</Link> / Coaching &amp; Mentoring</>}
        eyebrow="Support Services"
        title="Coaching &"
        highlight="Mentoring"
        description="Goal-focused, structured support for young people and adults ready to grow, build confidence, and unlock their potential."
      />
      <section className="content-section alt"><div className="container"><div className="two-col"><div><div className="section-label">The Mentoring Difference</div><h2 className="section-title">Mentoring for Young People and Adults</h2><hr className="divider" /><p style={{fontSize: '.97rem', color: 'var(--text-muted)', lineHeight: 1.8, marginBottom: '1.25rem'}}>Mentorship is to influence, guide, or direct a mentee - by teaching them, giving help and advice to a less experienced and often younger person. The mentor may also influence the mentee in both a personal and professional capacity.</p><p style={{fontSize: '.97rem', color: 'var(--text-muted)', lineHeight: 1.8, marginBottom: '1.5rem'}}><strong style={{color: 'var(--purple)'}}>The key difference</strong> between mentoring and coaching is that mentorship tends to focus on broader personal and professional development, whereas coaching often emphasizes specific tasks or objectives with more structured accountability.</p><blockquote style={{fontFamily: "'Cormorant Garamond',Georgia,serif", fontSize: '1.3rem', fontStyle: 'italic', color: 'var(--purple)', lineHeight: 1.5, borderLeft: '3px solid var(--gold)', paddingLeft: '1.25rem', marginBottom: '1.75rem'}}>“Establishing clear expectations early ensures a successful mentor–mentee relationship.”</blockquote><Link href="/contact" className="btn-gold" style={{marginRight: '.75rem'}}>Book a Session</Link><Link href="/contact" className="btn-outline">Free Consultation</Link></div><div style={{display: 'flex', flexDirection: 'column', gap: '1.25rem'}}><div className="card" style={{background: 'var(--purple-pale)'}}><span className="card-icon">🎯</span><h3>Strategy</h3><p>Mentorship strategies include establishing trust and rapport through active listening, setting clear and achievable goals, providing constructive and honest feedback, and encouraging a growth mindset throughout the engagement.</p></div><div className="card"><span className="card-icon">🤝</span><h3>Implementation</h3><p>Tools include structured mentoring agreement templates covering meeting frequency, communication preferences, confidentiality, conflict resolution, goal setting, and career development. Clear expectations from the start ensure success.</p></div></div></div></div></section>
      <section className="content-section" style={{background: 'var(--cream)'}}><div className="container"><div style={{textAlign: 'center', marginBottom: '3rem'}}><div className="section-label">Who This Is For</div><h2 className="section-title">Coaching &amp; Mentoring Programs</h2></div><div className="three-col"><div className="card"><span className="card-icon">🧒</span><h3>Youth (Ages 13–20)</h3><p>Structured mentoring for teenagers and young adults navigating school pressures, social challenges, career direction, and building a positive sense of self.</p><div className="tag-row"><span className="tag">Academic</span><span className="tag">Social</span><span className="tag">Career</span></div></div><div className="card"><span className="card-icon">👨‍👩‍👧</span><h3>Parents</h3><p>Coaching for parents who want practical strategies to support their children&apos;s development, improve communication, and reduce family stress and conflict.</p><div className="tag-row"><span className="tag">Communication</span><span className="tag">Boundaries</span><span className="tag">Support</span></div></div><div className="card"><span className="card-icon">🌟</span><h3>Adults</h3><p>Goal-oriented coaching for adults ready to make meaningful changes - career transitions, building healthy habits, improving relationships, or gaining clarity on next steps.</p><div className="tag-row"><span className="tag">Goals</span><span className="tag">Accountability</span><span className="tag">Growth</span></div></div></div></div></section>
      <div className="cta-strip"><div className="container"><h2>Ready to grow?</h2><p>Book a free 20-minute discovery call to explore whether coaching or mentoring is the right fit for you.</p><Link href="/contact" className="btn-gold">Book Free Consultation</Link></div></div>
    </>
  );
}
