import {Link} from '@/i18n/navigation';
import PageHero from '@/components/PageHero';

export default function CounselingTherapyPage() {
  return (
    <>
      <PageHero
        breadcrumb={<><Link href="/">Home</Link> / <Link href="/services">Support Services</Link> / Counseling &amp; Therapy</>}
        eyebrow="Support Services"
        title="Counseling &"
        highlight="Therapy"
        description="Customized, evidence-based mental health counseling delivered with empathy and clinical expertise - for children, adolescents, and adults."
      />
      <section className="content-section alt"><div className="container"><div className="two-col"><div><div className="section-label">Our Approach</div><h2 className="section-title">Customized Counseling for Your Needs</h2><hr className="divider" /><p style={{fontSize: '.97rem', color: 'var(--text-muted)', lineHeight: 1.8, marginBottom: '1.25rem'}}><strong style={{color: 'var(--purple)'}}>Cognitive Behavioral Therapy (CBT)</strong> is a type of psychotherapy that aims to reduce symptoms of various mental health conditions, primarily depression and disorders such as post-traumatic stress disorder and anxiety disorders. CBT focuses on challenging unhelpful and irrational negative thoughts - referred to as &quot;self-talk&quot; - and replacing them with more rational positive self-talk, producing less anxiety and depression.</p><p style={{fontSize: '.97rem', color: 'var(--text-muted)', lineHeight: 1.8, marginBottom: '1.5rem'}}><strong style={{color: 'var(--purple)'}}>Acceptance and Commitment Therapy (ACT)</strong> emphasizes acceptance to deal with negative thoughts, feelings, symptoms, or circumstances while encouraging increased commitment to healthy, constructive activities that uphold one&apos;s values or goals.</p><Link href="/contact" className="btn-gold" style={{marginRight: '.75rem'}}>Book a Session</Link><Link href="/contact" className="btn-outline">Free Consultation</Link></div><div style={{display: 'flex', flexDirection: 'column', gap: '1.25rem'}}><div className="card" style={{background: 'var(--purple-pale)'}}><span className="card-icon">💬</span><h3>Strategy: Socratic Questioning</h3><p>A technique used in CBT that helps clients move beyond tunnel-vision thinking and consider new perspectives through logical, reflective questions. It supports clients in understanding negative core beliefs and distinguishing between thoughts, feelings, and behaviors.</p></div><div className="card"><span className="card-icon">📋</span><h3>Implementation Tools</h3><p>CBT uses a variety of tools including behavioral activation worksheets, cognitive restructuring exercises, automatic thought records, journaling, guided discovery, and exposure therapy techniques.</p></div></div></div></div></section>
      <section className="content-section" style={{background: 'var(--cream)'}}><div className="container"><div style={{textAlign: 'center', marginBottom: '3rem'}}><div className="section-label">What We Address</div><h2 className="section-title">Areas of Focus</h2></div><div className="three-col"><div className="card"><span className="card-icon">😰</span><h3>Anxiety &amp; Stress</h3><p>Practical tools to identify anxiety triggers, interrupt worry cycles, and build lasting coping skills for daily stressors.</p></div><div className="card"><span className="card-icon">💙</span><h3>Depression &amp; Low Mood</h3><p>Behavioural activation and cognitive restructuring to counter low motivation, fatigue, and persistent negative self-talk.</p></div><div className="card"><span className="card-icon">👨‍👩‍👧</span><h3>Parenting Pressures</h3><p>Support for parents navigating the challenges of raising children with behavioral, developmental, or emotional concerns.</p></div><div className="card"><span className="card-icon">🔄</span><h3>Life Transitions</h3><p>Guidance through major changes - career shifts, relationship changes, grief, and the stress of navigating the unexpected.</p></div><div className="card"><span className="card-icon">🧒</span><h3>Child &amp; Adolescent</h3><p>Specialized support for ages 3–18, drawing on developmental theories and ABA to build foundational emotional skills.</p></div><div className="card"><span className="card-icon">🕊️</span><h3>Trauma &amp; PTSD</h3><p>Evidence-based approaches to process traumatic experiences and reduce their impact on daily functioning and relationships.</p></div></div></div></section>
      <div className="cta-strip"><div className="container"><h2>Take the first step toward lasting peace.</h2><p>Book a free 20-minute consultation - no commitment, just a conversation.</p><Link href="/contact" className="btn-gold">Book Free Consultation</Link></div></div>
    </>
  );
}
